export const products = [
  {
    id: "prod_1",
    name: "The Starter Kit",
    slug: "starter-kit",
    price: 39.99,
    description: "Everything you need to start your matcha ritual at home.",
    long_description: "Our Starter Kit includes premium ceremonial-grade matcha, a traditional bamboo whisk (chasen), a measuring spoon (chashaku), and a beautifully designed glass. Plus a bottle of our signature lavender vanilla syrup to make your first cup unforgettable. Step-by-step ritual guide included.",
    origin: "Uji, Kyoto, Japan",
    flavor_profile: "Smooth, sweet, and subtly vegetal with zero bitterness",
    ingredients: "Ceremonial-grade matcha powder, bamboo whisk, bamboo scoop, glass tumbler, lavender vanilla syrup (60ml)",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/96867ff54_generated_6db67f9d.png",
    image_url_2: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/1f8727042_generated_6d7d9edb.png",
    category: "starter_kit",
    featured: true,
    in_stock: true,
    created_date: "2026-03-20T10:00:00Z",
  },
  {
    id: "prod_2",
    name: "The Premium Kit",
    slug: "premium-kit",
    price: 69.99,
    description: "The full barista experience — matcha, cold foam, syrups, and tools.",
    long_description: "Our Premium Kit elevates your home matcha game to café level. Includes our highest-grade ceremonial matcha, an electric frother for silky cold foam, two handmade syrups of your choice, a bamboo whisk, and a double-wall glass. Everything you need to craft Instagram-worthy matcha drinks daily.",
    origin: "Nishio, Aichi, Japan",
    flavor_profile: "Rich umami, naturally sweet with a creamy finish",
    ingredients: "Premium ceremonial-grade matcha, electric frother, bamboo whisk, double-wall glass, 2x handmade syrups (120ml each)",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/d08187dd0_generated_2fee63d1.png",
    image_url_2: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/7b7413b7c_generated_01d92689.png",
    category: "premium_kit",
    featured: true,
    in_stock: true,
    created_date: "2026-03-18T10:00:00Z",
  },
  {
    id: "prod_3",
    name: "Ceremonial Matcha Tin",
    slug: "ceremonial-matcha-tin",
    price: 34.99,
    description: "30g of our finest stone-ground ceremonial matcha.",
    long_description: "Sourced from first-harvest leaves in Uji, Kyoto — shade-grown for 21 days to maximize L-theanine and chlorophyll. Stone-ground to a fine, vibrant green powder. Smooth, naturally sweet, and never bitter. Perfect for lattes, cold foam drinks, or traditional preparation.",
    origin: "Uji, Kyoto, Japan",
    flavor_profile: "Bright, sweet, with delicate umami notes",
    ingredients: "100% organic ceremonial-grade matcha (Camellia sinensis)",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/96867ff54_generated_6db67f9d.png",
    category: "matcha_only",
    featured: true,
    in_stock: true,
    created_date: "2026-03-15T10:00:00Z",
  },
];

export const syrups = [
  {
    id: "syr_1",
    name: "Lavender Vanilla",
    description: "Floral lavender meets warm Madagascar vanilla. Our bestseller.",
    price: 12.99,
    color_hex: "#B39DDB",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/7b7413b7c_generated_01d92689.png",
    in_stock: true,
    created_date: "2026-03-22T10:00:00Z",
  },
  {
    id: "syr_2",
    name: "Honey Ginger",
    description: "Raw wildflower honey with a gentle ginger kick. Warming and sweet.",
    price: 12.99,
    color_hex: "#FFB74D",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/d08187dd0_generated_2fee63d1.png",
    in_stock: true,
    created_date: "2026-03-21T10:00:00Z",
  },
  {
    id: "syr_3",
    name: "Vanilla Bean",
    description: "Pure vanilla bean paste in a simple syrup. Classic and smooth.",
    price: 11.99,
    color_hex: "#FFF9C4",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/1f8727042_generated_6d7d9edb.png",
    in_stock: true,
    created_date: "2026-03-20T10:00:00Z",
  },
  {
    id: "syr_4",
    name: "Brown Sugar",
    description: "Rich Okinawan brown sugar with deep caramel notes.",
    price: 12.99,
    color_hex: "#A1887F",
    image_url: "https://media.base44.com/images/public/69c68ea8ad04082f2770efa3/96867ff54_generated_6db67f9d.png",
    in_stock: true,
    created_date: "2026-03-19T10:00:00Z",
  },
];
